# Generated by Django 5.0.2 on 2024-02-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("doctor", models.CharField(max_length=255)),
                ("arrival_date", models.DateField()),
                ("arrival_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name_english", models.CharField(max_length=255)),
                ("patient_name_bangla", models.CharField(max_length=255)),
                ("patient_father_name_english", models.CharField(max_length=255)),
                ("patient_father_name_bangla", models.CharField(max_length=255)),
                ("patient_mother_name_english", models.CharField(max_length=255)),
                ("patient_mother_name_bangla", models.CharField(max_length=255)),
                ("present_address", models.TextField()),
                ("permanent_address", models.TextField()),
                ("mobile_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("nid_or_birth_certificate_no", models.CharField(max_length=255)),
                ("sex", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
    ]
