# Generated by Django 5.0.1 on 2024-02-08 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_patient_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nid_or_birth_certificate_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='permanent_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='present_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(),
        ),
    ]
